### ISSUE TITLE
clean up redis / db layer

### ISSUE THREAD

**Issue by kulicuu** [rfcx/rfcx-worker-analysis#12]
- make `register` a private function to be called by `update_model` when the station isn't already extistent / registered.

- `get_model` should return `None` when the station doesn't exist, or for some reason the lists are empty -- (shouldn't be the case if `register_station` is private.

- remove inline testing debris

**Comment by flygeneticist** [comment]
Hi Wylie. Can you look into the Redis DB layer either today or tomorrow? The CLI is crashing due to a TypeError exception. Thanks!

**Comment by kulicuu** [comment]
Yes definitely !
